title: "Better StimulusJS"
remote_theme: pmarsceill/just-the-docs
aux_links:
  "Github":
    - "//github.com/julianrubisch/better-stimulus"
plugins:
  - jekyll-relative-links
relative_links:
  enabled:     true
  collections: true
