title: "Better StimulusJS"
remote_theme: pmarsceill/just-the-docs
url: "https://www.betterstimulus.com"
aux_links:
  "Github":
    - "//github.com/julianrubisch/better-stimulus"
plugins:
  - jekyll-relative-links
  - jekyll-analytics
relative_links:
  enabled:     true
  collections: true
jekyll_analytics:
  GoogleAnalytics:
    id: UA-159938381-1
